### ISSUE TITLE
websocket is not defined

### ISSUE THREAD

**Issue by MRashwan41** [hamsa-ai/voice-agents-sdk#1]
i was trying to build a nodejs app using voice-agents-sdk
![{20C01610-C6E1-4EFF-BCE1-82391F6E3540}](https://github.com/user-attachments/assets/826dcdba-ba42-4161-9251-4943c9c691c4)
we are trying to use it in our pbx to initiate calls 
plus i can't find any docs about voice enablment 
need help 
thanks in advanced

**Comment by ibrahiemj** [comment]
Hello @MRashwan41, This package is designed for browser environments, it can be used in React, Angular, Vanilla Javascript, or any other framework, unfortunately, it will not run in NodeJs as it depends on browser SDKs.

You can use our APIs to integrate it with your PBX, we would love to help and support you with this, you can reach out to support@tryhamsa.com so we can schedule a call and take this further.

Thank you

**Comment by MRashwan41** [comment]
thanks for the help and grateful for your support
